{{- if (.Values.hpa.enabled) -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lightstep-satellite.fullname" . }}
  labels:
    {{- include "lightstep-satellite.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lightstep-satellite.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  # PR #18965 reverts the previous pull request since the behavior object is functionality targeted in 1.18, not 1.17.
  # {{- with .Values.hpa.behavior }}
  # behavior:
  #   {{- toYaml . | nindent 4 }}
  # {{- end }}
  {{- with .Values.hpa.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
