{{- if gt .Values.podDisruptionBudget.minAvailable "0" }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lightstep-satellite.fullname" . }}
  labels:
    {{- include "lightstep-satellite.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "lightstep-satellite.selectorLabels" . | nindent 6 }}
{{- end }}
