# Traefik Ingress Route
---
{{- if (.Values.traefik.ingressRoute.enabled) -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "lightstep-satellite.fullname" . }}
  labels:
    {{- include "lightstep-satellite.labels" . | nindent 4 }}
spec:
  routes:
    - match: PathPrefix(`{{ .Values.traefik.ingressRoute.pathPrefix }}`)
      kind: Rule
      middlewares:
        - name: "{{ include "lightstep-satellite.fullname" . }}-retry"
      services:
        {{ if .Values.service.collector.insecure.enabled }}
        - name: {{ include "lightstep-satellite.fullname" . }}
          port: 80
        {{- end }}

        {{- if .Values.service.collector.secure.enabled }}
        - name: {{ include "lightstep-satellite.fullname" . }}
          port: 443
          scheme: https
        {{- end }}

    - match: PathPrefix(`{{ .Values.traefik.ingressRoute.pathPrefix }}api/v2`)
      kind: Rule
      services:
        {{ if .Values.service.collector.insecure.enabled }}
        - name: {{ include "lightstep-satellite.fullname" . }}
          port: 80
        {{- end }}

        {{- if .Values.service.collector.secure.enabled }}
        - name: {{ include "lightstep-satellite.fullname" . }}
          port: 443
          scheme: https
        {{- end }}
    - match: PathPrefix(`{{ .Values.traefik.ingressRoute.pathPrefix }}diagnostics`)
      kind: Rule
      services:
        {{ if .Values.service.diagnostics.enabled }}
        - name: {{ include "lightstep-satellite.fullname" . }}
          port: 8000
        {{- end }}
    - match: PathPrefix(`{{ .Values.traefik.ingressRoute.pathPrefix }}admin`)
      kind: Rule
      services:
        - name: {{ include "lightstep-satellite.fullname" . }}
          port: {{ .Values.service.admin.port }}
{{- end -}}

